name: GetChangelogEntry

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        continue-on-error: true
      - name: get merge commit message 
        id: pull
        run: |
         pull_number="$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" 
         commit_message="$(git log --pretty="format:%b")"
         echo "$commit_message" [GH-$pull_number]>> changelog_entry.txt
      - uses: actions/upload-artifact@v4
        with:
            name: changelog_entry
            path: changelog_entry.txt
            overwrite: true