name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: save the merge commit message body
      run: echo COMMIT_MSG="$(git log --pretty="format:%b")" >> $GITHUB_ENV
  # check-for-changelog-entry:
  changelog-entry:
    # if: ${{ contains(env.COMMIT_MSG, [BUG]) }}
    runs-on: ubuntu-latest
    steps:
    - name: check if bug
      run: echo "$COMMIT_MSG"
  # if contains to check for bug, enhancement, breaking change, feature
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: check for a changelog PR, if no PR, open one, append entry to PR
      run: echo "Adding changelog entry to changelog.md - nothing for now"
