name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Get sha of the merge commit
      run: echo "COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"" >> $GITHUB_ENV
    - name: add sha to a url
      run: echo "COMMIT_URL="https://api.github.com/repos/rcskosir/Issues_GitHubActions/git/commits/$COMMIT_SHA"" >> $GITHUB_ENV
    - name: get the json from the url, pull commit from json
      run: echo "COMMIT_MSG=$(curl -sf $COMMIT_URL | jq .message)" >> $GITHUB_ENV
    - name: echo out the commit message
      run: echo "$COMMIT_MSG"
    - name: splite title and body
      run: echo "::set-output name=message::${COMMIT_MSG##*\n\n}"
  # isolate-squash-merge-commit:
  # regex to get just the commit message, not the title
  # check-for-changelog-entry:
  # regex to check for bug, enhancement, breaking change, feature
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: check for a changelog PR, if no PR, open one, append entry to PR
      run: echo "Adding changelog entry to changelog.md - nothing for now"
