name: Update Changelog PR

permissions:
  pull-requests: write
  contents: write

on:
  workflow_run:
    workflows: [GetChangelogEntry]
    types:
      - completed

jobs:
  # if there is a changelog entry, check for PR Open
  update-changelog:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.pull.outputs.message }}
    steps:
      - name: Get run ID of "Test" workflow
        id: get-run-id
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="GetChangelogEntry"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact from "Get Changelog Entry" workflow
        uses: actions/download-artifact@v4
        with:
          name: changelog_entry # Match name used in changelog_entry.yml upload artifact step
          path: . # Download to the current working directory of this job
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
      - name: Check if PR exists
        id: check
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json title \
              --label "changelog" \
              --jq 'length')
          if [[  $prs -gt 0  ]]; then
              echo "existing=true" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/checkout@v4
      - name: check for branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: |
          BRANCH=automated-changelog
          #TODO CHANGE API CALL BELOW TO MATCH AZURE REPO
          if gh api repos/rcskosir/Issues_GitHubActions/branches/$BRANCH > /dev/null 2>&1; then
            echo "Branch exists on remote..."
            git fetch origin $BRANCH
            git checkout $BRANCH
          else
            echo "Branch does not exist on remote, creating locally..."
            git checkout -b $BRANCH
          fi
          
      - name: Create pull request
      #if changelog PR isn't already open, open one
      #create a new PR, start with appending the release number and (unreleased)
        if: '!steps.check.outputs.existing'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          #new pull request for new release needs the headers all added to the top
          FILE="CHANGELOG.md"
          version=$(head -n 1 "$FILE")
          IFS='.' read major minor patch <<< "$version"
          ((minor++))
          patch=$(echo $patch | sed 's/ (.*)//')
          new_version="${major}.$minor.${patch} (Unreleased)"
          headers="${new_version}\n\nENHANCEMENTS:\n\nFEATURES:\n\nBUG FIXES:\n"
          temp_file=$(mktemp)
          echo -e "$headers" > "$temp_file"
          cat "$FILE" >> "$temp_file"
          mv "$temp_file" "$FILE"
          echo "File has been updated."

          major=$(echo $major | sed 's/## //')
          RELEASENUM="${major}.$minor.${patch}"

          git add CHANGELOG.md
          git commit -m "staring new changelog PR"
          git push --set-upstream origin automated-changelog
          echo "Creating a new pull request"
          gh pr create \
          --repo "$GITHUB_REPOSITORY" \
          --base main \
          --head automated-changelog \
          -l "changelog" \
          -t "CHANGELOG.md for $RELEASENUM" \
          -b "Automated changelog for next release, $RELEASENUM"
      
      - name: Set up Go
        uses: actions/setup-go@v3  # Set up go
        with:
          go-version: '1.20'
      
      - name: Add commit message to changelog pull request
      # at this point a PR is opened for sure, now add entry
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          go run ./.github/workflows/update_changelog.go CHANGELOG.md changelog_entry.txt
          
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push --set-upstream origin automated-changelog
      
