name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Get sha of the merge commit
      run: echo "git log --pretty="format:%b""
  # check-for-changelog-entry:
  # if contains to check for bug, enhancement, breaking change, feature
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: check for a changelog PR, if no PR, open one, append entry to PR
      run: echo "Adding changelog entry to changelog.md - nothing for now"
