name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get changelog entry
      run: echo "${{ github.event.pull_request.squash_merge_commit_message }}"
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: check for a changelog PR, if no PR, open one, append entry to PR
      run: echo "Adding changelog entry to changelog.md - nothing for now"
