name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request_target:
    # Inputs the workflow accepts.
    types: [closed] #and merged?

jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get changelog entry
      run: echo "Pulling commit message from merged PR"
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Update changelog
      run: echo "Adding changelog entry to changelog.md"
