name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request_target:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get changelog entry
      run: git log -1 --pretty=format:"%s"
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Update changelog
      run: echo "Adding changelog entry to changelog.md - nothing for now"
