name: Update Changelog with new commit

permissions:
  pull-requests: write

on:
  pull_request:
    # Inputs the workflow accepts.
    types: [closed]

jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v4
      - name: get commit message 
        id: step1
        run: echo test="$(git log --pretty="format:%b")" >> $GITHUB_OUTPUT
  # check-for-changelog-entry
  changelog-entry:
    if: ${{ contains(needs.pull-commit-message.outputs.message, '[BUG]') }}
    runs-on: ubuntu-latest
    needs: pull-commit-message
    steps:
      - name: is a BUG
        run: echo "BUG entry"
  # if contains to check for bug, enhancement, breaking change, feature
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: check for a changelog PR, if no PR, open one, append entry to PR
      run: echo "Adding changelog entry to changelog.md - nothing for now"
